# Site settings
author: Bryce Boddy
title: First Mile into Code Bootcamp
header-img: img/home-bg.png
email: bryce.boddy@gmail.com
copyright_name: Bryce Boddy
description: > # this means to ignore newlines until "baseurl:"
  First Mile
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Bboddy

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
